--µ÷ÓÃ·½·¨
--select dbo.fn_Spell('ÖÐ¹ú')

set ANSI_NULLS ON
set QUOTED_IDENTIFIER ON
GO
ALTER function [dbo].[fn_Spell](@words nvarchar(10)) 
returns varchar(20) 
as 
begin 
declare @word nchar(1) 
declare @pinyin varchar(20) 
declare @i int 
declare @words_len int 
declare @unicode int 
set @i = 1 
set @words = ltrim(rtrim(@words)) 
set @words_len = len(@words) 
while (@i <= @words_len) --Ñ­»·È¡×Ö·û 
begin 
set @word = substring(@words, @i, 1) 
set @unicode = unicode(@word) 
set @pinyin = ISNULL(@pinyin+space(1),'')+ 
(case when unicode(@word) between 19968 and 19968+20901 then 
(select top 1 py from ( 
select 'a' as py,N'…' as word 
union all select 'ai',N'ìa' 
union all select 'an',N'÷ö' 
union all select 'ang',N'ál' 
union all select 'ao',N'òˆ' 
union all select 'ba',N'™ñ' 
union all select 'bai',N'®B' --ívƒÄ®B 
union all select 'ban',N'°ê' 
union all select 'bang',N'æ^' 
union all select 'bao',N'èt' 
union all select 'bei',N'öÍ' 
union all select 'ben',N'Ý™' 
union all select 'beng',N'ça' 
union all select 'bi',N'ü„' 
union all select 'bian',N'×ƒ' 
union all select 'biao',N'÷B' 
union all select 'bie',N'•' 
union all select 'bin',N'ôW' 
union all select 'bing',N'ìh' 
union all select 'bo',N'ÊN' 
union all select 'bu',N'²¾' 
union all select 'ca',N'‡Í' 
union all select 'cai',N'k' --¿nk 
union all select 'can',N' |' 
union all select 'cang',N'Ù‰' 
union all select 'cao',N'ü' 
union all select 'ce',N'ºu' 
union all select 'cen',N'¸’' 
union all select 'ceng',N'u' --³€³’Kªeu 
union all select 'cha',N'ÔŒ' 
union all select 'chai',N'‡Ð' 
union all select 'chan',N'î' 
union all select 'chang',N'ío' 
union all select 'chao',N'Óe' 
union all select 'che',N' …' 
union all select 'chen',N'×' 
union all select 'cheng',N'³Ó' 
union all select 'chi',N'úu' 
union all select 'chong',N'ã|' 
union all select 'chou',N'šŽ' 
union all select 'chu',N'´£' 
union all select 'chuai',N'õß' 
union all select 'chuan',N'úE' 
union all select 'chuang',N'í' 
union all select 'chui',N'îq' 
union all select 'chun',N'´À' 
union all select 'chuo',N'¿W' 
union all select 'ci',N'†ï' --Ùn†ï 
union all select 'cong',N'Ö' 
union all select 'cou',N'Ý' 
union all select 'cu',N'î•' 
union all select 'cuan',N'ìà' 
union all select 'cui',N'Ä›' 
union all select 'cun',N'»v' 
union all select 'cuo',N'åe' 
union all select 'da',N'™\' 
union all select 'dai',N'ì^' 
union all select 'dan',N'ð…' 
union all select 'dang',N'êW' 
union all select 'dao',N'ôî' 
union all select 'de',N'µÄ' 
union all select 'den',N'’Y' 
union all select 'deng',N'ç‹' 
union all select 'di',N'ÏE' 
union all select 'dia',N'àÇ' 
union all select 'dian',N'ò›' 
union all select 'diao',N'èS' 
union all select 'die',N'‡Ã' --±‚‡Ã 
union all select 'ding',N'îr' 
union all select 'diu',N'äA' 
union all select 'dong',N'ëš' 
union all select 'dou',N'ôa' 
union all select 'du',N'ó¼' 
union all select 'duan',N'…¶' --»f…¶ 
union all select 'dui',N'×m' 
union all select 'dun',N'Ûv' 
union all select 'duo',N'ùz' 
union all select 'e',N'÷{' 
union all select 'en',N'Þô' 
union all select 'eng',N'íE' 
union all select 'er',N'˜Þ' 
union all select 'fa',N'óŒ' 
union all select 'fan',N'ž~' 
union all select 'fang',N'·Å' 
union all select 'fei',N'ì]' 
union all select 'fen',N'÷a' 
union all select 'feng',N'Ò…' 
union all select 'fo',N'—‚' 
union all select 'fou',N'ø]' 
union all select 'fu',N'ªg' --övªg 
union all select 'ga',N'ôp' 
union all select 'gai',N'­y' 
union all select 'gan',N'ž¸' 
union all select 'gang',N'‘ß' 
union all select 'gao',N'ä†' 
union all select 'ge',N'ª˜' 
union all select 'gei',N'½o' 
union all select 'gen',N'“j' 
union all select 'geng',N'ˆí' --ƒˆí†¯†Ö†ñ 
union all select 'gong',N'ƒÅ' --ŸËÚCƒÀƒÅ 
union all select 'gou',N'Ù' 
union all select 'gu',N'î™' 
union all select 'gua',N'ÔŸ' 
union all select 'guai',N's' 
union all select 'guan',N'÷}' 
union all select 'guang',N'“Ñ' 
union all select 'gui',N'÷i' 
union all select 'gun',N'Ö' 
union all select 'guo',N'ÄB' 
union all select 'ha',N'¹þ' 
union all select 'hai',N'ðŽ' 
union all select 'han',N'ú[' 
union all select 'hang',N'ãì' 
union all select 'hao',N'ƒÁ' 
union all select 'he',N'ìg' 
union all select 'hei',N'‹Ï' 
union all select 'hen',N'ºÞ' 
union all select 'heng',N'ˆý' --ˆý‡Ö 
union all select 'hong',N'ô\' 
union all select 'hou',N'÷c' 
union all select 'hu',N'ûI' 
union all select 'hua',N'Ìs' 
union all select 'huai',N'Ì|' 
union all select 'huan',N'öd' 
union all select 'huang',N'æw' 
union all select 'hui',N'îœ' 
union all select 'hun',N'ÕŸ' 
union all select 'huo',N'‰þ' 
union all select 'ji',N'óK' 
union all select 'jia',N'†í' 
union all select 'jian',N'èƒ' 
union all select 'jiang',N'Ö˜' 
union all select 'jiao',N'á†' 
union all select 'jie',N'ÀT' 
union all select 'jin',N'ý„' 
union all select 'jing',N'¸„' 
union all select 'jiong',N'ÌW' 
union all select 'jiu',N'™ã' 
union all select 'ju',N' „' 
union all select 'juan',N'Á\' 
union all select 'jue',N'è‘' 
union all select 'jun',N'”h' 
union all select 'ka',N'ãl' 
union all select 'kai',N'f' --æbf 
union all select 'kan',N'²™' 
union all select 'kang',N'é`' 
union all select 'kao',N'õ‘' 
union all select 'ke',N'òS' 
union all select 'ken',N'Ñy' 
union all select 'keng',N'çH' --Ž|g†{…ž] 
union all select 'kong',N'W' 
union all select 'kou',N'úd' 
union all select 'ku',N'‡¿' 
union all select 'kua',N'óg' 
union all select 'kuai',N'÷d' 
union all select 'kuan',N'¸U' 
union all select 'kuang',N'èk' 
union all select 'kui',N'è^' 
union all select 'kun',N'±—' 
union all select 'kuo',N'·i' 
union all select 'la',N'íB' 
union all select 'lai',N'»[' 
union all select 'lan',N'¼h' 
union all select 'lang',N'†}' 
union all select 'lao',N'Ü~' 
union all select 'le',N'ðE' 
union all select 'lei',N'Ãš' --àÏÃš 
union all select 'leng',N'±œ' 
union all select 'li',N'­€' 
union all select 'lia',N'‚z' 
union all select 'lian',N'À~' 
union all select 'liang',N'åy' 
union all select 'liao',N'²t' 
union all select 'lie',N'÷v' 
union all select 'lin',N'Þ`' --Þ`Áà 
union all select 'ling',N'žâ' 
union all select 'liu',N'¿©' --®F®M‡Þ¿© 
union all select 'long',N'ÚL' 
union all select 'lou',N'çU' 
union all select 'lu',N'ëª' 
union all select 'lv',N'èr' 
union all select 'luan',N'y' 
union all select 'lue',N'”^' 
union all select 'lun',N'Õ“' 
union all select 'luo',N'÷w' 
union all select 'ma',N'Âï' 
union all select 'mai',N'ìA' 
union all select 'man',N'Ìp' 
union all select 'mang',N'Ï‘' 
union all select 'mao',N'†x' 
union all select 'me',N'°Z' --°Z…Ð 
union all select 'mei',N'‡ª' 
union all select 'men',N'‚ƒ' 
union all select 'meng',N'ìD' --ìWÛ_ 
union all select 'mi',N'Á]' 
union all select 'mian',N'üI' 
union all select 'miao',N'R' 
union all select 'mie',N'÷x' --÷x­Ÿ 
union all select 'min',N'öš' 
union all select 'ming',N'Ôš' 
union all select 'miu',N'Ö‡' 
union all select 'mo',N'ñò' --ñòi 
union all select 'mou',N'üE' --üEÏw 
union all select 'mu',N'”æ' 
union all select 'na',N'ô›' 
union all select 'nai',N'år' 
union all select 'nan',N'‹R' 
union all select 'nang',N'ýQ' 
union all select 'nao',N'Äž' 
union all select 'ne',N'ÄØ' 
union all select 'nei',N'Ÿˆ' --ÄÛŸˆ 
union all select 'nen',N'ÄÛ' 
union all select 'neng',N'ÄÜ' --Ç‚àÅâ…äG†« 
union all select 'ni',N'‹ò' 
union all select 'nian',N'Åˆ' 
union all select 'niang',N'á„' 
union all select 'niao',N'ëå' 
union all select 'nie',N'è' 
union all select 'nin',N'’Œ' 
union all select 'ning',N'ô' 
union all select 'niu',N'ì' 
union all select 'nong',N'ýP' 
union all select 'nou',N'×k' 
union all select 'nu',N'“x' 
union all select 'nv',N'ô¬' 
union all select 'nue',N'¯‘' 
union all select 'nuan',N' \' --³–üQ \àG 
union all select 'nuo',N'–þ' 
union all select 'o',N'íM' --šÄ‰ñjíM 
union all select 'ou',N'a' 
union all select 'pa',N'Ð’' 
union all select 'pai',N'´s' --æW´s 
union all select 'pan',N'è‹' 
union all select 'pang',N'ÅÖ' 
union all select 'pao',N'µ^' 
union all select 'pei',N'Þ\' 
union all select 'pen',N'†Ï' 
union all select 'peng',N'†Ô' --›¹Ž‡êCn†Ô 
union all select 'pi',N'ûG' 
union all select 'pian',N'ò_' 
union all select 'piao',N'‘G' 
union all select 'pie',N'‹±' 
union all select 'pin',N'Æ¸' 
union all select 'ping',N'ÌO' 
union all select 'po',N'ÆÇ' 
union all select 'pou',N'†R' --ƒÍ†R 
union all select 'pu',N'ÆØ' 
union all select 'qi',N'Ï„' 
union all select 'qia',N'÷Ä' 
union all select 'qian',N'¿y' 
union all select 'qiang',N'­™' --Á†ƒ¿­™ 
union all select 'qiao',N'ÜN' 
union all select 'qie',N'»]' 
union all select 'qin',N'ÌC' 
union all select 'qing',N'™¼' 
union all select 'qiong',N'­Ž' 
union all select 'qiu',N'ôÜ' 
union all select 'qu',N'ÓY' 
union all select 'quan',N'„ñ' 
union all select 'que',N'µ]' 
union all select 'qun',N'‡Ý' 
union all select 'ran',N'™L' 
union all select 'rang',N'×Œ' 
union all select 'rao',N'À@' 
union all select 're',N'Ÿá' 
union all select 'ren',N'ïš' 
union all select 'reng',N'ê—' 
union all select 'ri',N'ñ_' 
union all select 'rong',N'·\' 
union all select 'rou',N'Ž]' 
union all select 'ru',N'”J' 
union all select 'ruan',N'µO' 
union all select 'rui',N'‰Ç' 
union all select 'run',N'˜ô' --˜ô’µ 
union all select 'ruo',N'úU' 
union all select 'sa',N'–Ó' --™¨–Ó 
union all select 'sai',N'Ìƒ' --º›Ìƒ 
union all select 'san',N'éd' 
union all select 'sang',N'†Ê' 
union all select 'sao',N'ó' 
union all select 'se',N'ïo' --ÑSÂ{ 
union all select 'sen',N'ºd' 
union all select 'seng',N'¿L' --é~¿L 
union all select 'sha',N'ö®' 
union all select 'shai',N'•ñ' 
union all select 'shan',N'÷X' 
union all select 'shang',N'¾y' 
union all select 'shao',N'äû' 
union all select 'she',N'™Ý' 
union all select 'shen',N'¯”' 
union all select 'sheng',N'Ù‹' 
union all select 'shi',N'­—' --ö|ýaƒ¾­— 
union all select 'shou',N'æ' 
union all select 'shu',N'Ì ' 
union all select 'shua',N'ÕX' 
union all select 'shuai',N'…i' 
union all select 'shuan',N'ÄY' 
union all select 'shuang',N'ž“' 
union all select 'shui',N'Ë¯' 
union all select 'shun',N'ôB' 
union all select 'shuo',N'èp' 
union all select 'si',N'r' --ž[ÏAr 
union all select 'song',N'æ' 
union all select 'sou',N'¯˜' 
union all select 'su',N'ú‰' 
union all select 'suan',N'Ëã' 
union all select 'sui',N'ç›' 
union all select 'sun',N'–' 
union all select 'suo',N'ÎR' 
union all select 'ta',N'Òk' --ÜcÒk 
union all select 'tai',N' M' 
union all select 'tan',N'Ùy' 
union all select 'tang',N' C' 
union all select 'tao',N'®z' --Ó‘®z 
union all select 'te',N'Ïc' 
union all select 'teng',N'–Y' --ìL†z–Y 
union all select 'ti',N'ÚŒ' 
union all select 'tian',N'Åq' 
union all select 'tiao',N'¼g' 
union all select 'tie',N'÷Ñ' 
union all select 'ting',N'h' --ìh 
union all select 'tong',N'‘q' 
union all select 'tou',N'Í¸' 
union all select 'tu',N'ùr' 
union all select 'tuan',N'Ñ‰' 
union all select 'tui',N'òD' 
union all select 'tun',N'ˆd' 
union all select 'tuo',N'»X' 
union all select 'wa',N'í€' 
union all select 'wai',N'î“' 
union all select 'wan',N'Ú@' 
union all select 'wang',N'–R' 
union all select 'wei',N'Ü^' 
union all select 'wen',N'è·' 
union all select 'weng',N'ýN' 
union all select 'wo',N'ý}' 
union all select 'wu',N'úF' 
union all select 'xi',N'Ða' 
union all select 'xia',N'ç]' 
union all select 'xian',N'ýE' 
union all select 'xiang',N'÷P' 
union all select 'xiao',N'”Ã' 
union all select 'xie',N'õó' 
union all select 'xin',N'á…' 
union all select 'xing',N'ÅB' 
union all select 'xiong',N'”¸' 
union all select 'xiu',N'ýM' 
union all select 'xu',N'Þ£' 
union all select 'xuan',N'ÚK' 
union all select 'xue',N'žy' 
union all select 'xun',N'èR' 
union all select 'ya',N'ý…' 
union all select 'yan',N'ž¹' 
union all select 'yang',N'˜Ó' 
union all select 'yao',N'è€' 
union all select 'ye',N'Œè' --ûEÄŒŒè 
union all select 'yi',N'ý~' 
union all select 'yin',N'™’' 
union all select 'ying',N'×G' 
union all select 'yo',N'†Ñ' 
union all select 'yong',N'ák' 
union all select 'you',N'÷ø' 
union all select 'yu',N' Œ' 
union all select 'yuan',N'îŠ' 
union all select 'yue',N'ûV' 
union all select 'yun',N'í' 
union all select 'za',N'ë{' 
union all select 'zai',N'¿f' 
union all select 'zan',N'ð•' 
union all select 'zang',N'ÅK' 
union all select 'zao',N'¸^' 
union all select 'ze',N'¶' 
union all select 'zei',N'÷e' 
union all select 'zen',N'‡×' 
union all select 'zeng',N'Ù›' 
union all select 'zha',N'ám' 
union all select 'zhai',N'ñ©' 
union all select 'zhan',N'ò–' 
union all select 'zhang',N'²d' 
union all select 'zhao',N'Á^' 
union all select 'zhe',N'úp' 
union all select 'zhen',N'ül' 
union all select 'zheng',N'×C' 
union all select 'zhi',N'ØU' 
union all select 'zhong',N'ÖA' 
union all select 'zhou',N'óE' 
union all select 'zhu',N'èT' 
union all select 'zhua',N'×¦' 
union all select 'zhuai',N'ÛJ' 
union all select 'zhuan',N'»M' 
union all select 'zhuang',N'‘Þ' 
union all select 'zhui',N'èV' 
union all select 'zhun',N'¶›' 
union all select 'zhuo',N'»m' 
union all select 'zi',N'n' --n†€ 
union all select 'zong',N'¿v' 
union all select 'zou',N'‹ƒ' 
union all select 'zu',N'ÖŠ' 
union all select 'zuan',N'ß¬' 
union all select 'zui',N'™Þ' 
union all select 'zun',N'ã†' 
union all select 'zuo',N'…ø') t 
where word >= @word collate Chinese_PRC_CS_AS_KS_WS 
order by word ASC) else @word end) 
set @i = @i + 1 
end 
return replace(@pinyin,' ','')
END