SELECT * FROM SZMETROCS.DBO.SYS_SYNtRANS;

SELECT * FROM SZMETROCS.DBO.SYS_SYNRECORD ORDER BY SYSDATETIME DESC;

SELECT RESPONSE, SYSDATETIME FROM SZMETROCS.DBO.SYS_SYNRECORD GROUP BY RESPONSE, SYSDATETIME -- ORDER BY SYSDATETIME DESC;


SELECT * FROM SZMETROCS.DBO.SEC_USER WHERE USERCODE='203170';

SELECT * FROM SZMETROOA.DBO.SEC_USER WHERE USERCODE='203170';


