
/*
attribute11用于标示计划员退回，
return_flag用于标示采购员退回；
被计划退回的需求重新审批通过后，attribute11的“RETURN”信息会被清空，用于重新编制计划
*/
  SELECT rowid, L.HEADER_ID, L.CREATION_DATE,L.LAST_UPDATE_DATE
         ,L.ATTRIBUTE11, L.RETURN_FLAG, L.ATTRIBUTE15
         ,L.*
  FROM CUX_INV_DEMAND_LINES L
  WHERE HEADER_ID IN (SELECT HEADER_ID FROM CUX_INV_DEMAND_HEADERS 
                             WHERE DEMAND_CODE in ('SQ201603070001')) --('SQ01201603240001','SQ01201603240002'))
  ;
  
  /*
  SELECT L.ORGANIZATION_ID, H.DEMAND_CODE
         ,L.HEADER_ID, L.CREATION_DATE,L.LAST_UPDATE_DATE
         ,L.ATTRIBUTE11, L.RETURN_FLAG, L.ATTRIBUTE15
  FROM CUX_INV_DEMAND_LINES L
       ,CUX_INV_DEMAND_HEADERS H
  WHERE L.ATTRIBUTE11='RETURN' 
        AND RETURN_FLAG='Y'
        AND L.HEADER_ID=H.HEADER_ID
  order by L.LAST_UPDATE_DATE DESC        
        ;
  
