

--CUX_REPORT_PKG.P_PO_REPORT4;


SELECT DISTINCT  PRT.SEGMENT1,     --需求编码
                 prt.requisition_header_id,
                 prt.org_id,
             NVL(PPF.FULL_NAME,PRT.PREPARER_ID) FULL_NAME,    --编制人
             PRT.ATTRIBUTE1,   --需求类型
             TO_CHAR(PRT.CREATION_DATE,'YYYY-MM-DD') CREATION_DATE --创建日期
       FROM PO_REQUISITION_HEADERS_ALL PRT,
            PO_REQUISITION_LINES_ALL   PRL,
            PER_PEOPLE_F               PPF
      WHERE PPF.PERSON_ID(+) = PRT.PREPARER_ID 
       AND PRL.REQUISITION_HEADER_ID = PRT.REQUISITION_HEADER_ID
       AND PRT.SEGMENT1 BETWEEN NVL('JH201602170001',PRT.SEGMENT1) AND NVL('JH201602170001',PRT.SEGMENT1)
       AND PRT.AUTHORIZATION_STATUS = 'APPROVED'
       AND NVL(PRT.CANCEL_FLAG,'N')= 'N' 
/*       AND NVL(PRT.CLOSED_CODE ,'OPEN')= 'OPEN'*/
       AND NVL(PRL.CANCEL_FLAG,'N') = 'N'
/*       AND NVL(PRL.CLOSED_CODE,'OPEN')= 'OPEN'*/
       ORDER BY PRT.SEGMENT1 DESC;


      SELECT MSB.SEGMENT1,  --物资编号
             MSB.DESCRIPTION,--物资描述
             MCV.SEGMENT1||'.'||MCV.SEGMENT2||'.'||MCV.SEGMENT3 CATEGORY_CODE, --资产类别
             MSB.PRIMARY_UOM_CODE, --单位
             NVL(PRL.QUANTITY,0) QUANTITY,  --数量
             NVL(PRL.UNIT_PRICE,0) UNIT_PRICE, --单价
             NVL(PRL.QUANTITY,0)*NVL(PRL.UNIT_PRICE,0) TOTAL_AMOUNT --金额

        FROM PO_REQUISITION_HEADERS_ALL PRH,
             PO_REQUISITION_LINES_ALL   PRL,
             MTL_SYSTEM_ITEMS_B         MSB,
             MTL_CATEGORIES_V           MCV
       WHERE PRH.REQUISITION_HEADER_ID = PRL.Requisition_Header_Id
        and prl.requisition_header_id=252183
         AND MSB.INVENTORY_ITEM_ID = PRL.ITEM_ID
         AND MSB.ORGANIZATION_ID = PRL.DESTINATION_ORGANIZATION_ID
         AND MCV.CATEGORY_ID = PRL.CATEGORY_ID
         AND PRH.AUTHORIZATION_STATUS = 'APPROVED'
         AND PRH.SEGMENT1  = 'JH201602170001' --P_REQ_NUMBER
         AND PRH.ORG_ID = NVL(409,prh.org_id)
         AND NVL(PRL.CANCEL_FLAG,'N') = 'N'
;
