
SELECT * FROM CUX_INV_DEMAND_LINES L
WHERE L.HEADER_ID IN (SELECT HEADER_ID FROM CUX_INV_DEMAND_HEADERS H
                     WHERE H.DEMAND_CODE IN 'SQ02201409120001')
;

SELECT * FROM CUX_INV_TXN_LINES_V
WHERE MO_CODE LIKE 'SQ%'
      AND WORKORDER_TYPE='非生产性'
--WHERE MO_CODE='SQ02201409120001'
