
/*
  the  sql statement from foreground user function
SELECT ORGANIZATION_ID,DEMAND_HEADER_ID,DEMAND_LINE_ID,DEMAND_STATUS,INVENTORY_ITEM_ID,QUANTITY_OUT,QUANTITY_BACK,PLAN_HEADER_ID,PLAN_LINE_ID,PLAN_STATUS,REQ_STATUS,AUCTION_STATUS,AWARD_STATUS,SEALED_AUCTION_STATUS,PO_STATUS,PO_QUANTITY,LINE_LOCATION_ID,QUANTITY_ACCEPTED,QUANTITY_BILLED,DEMAND_CODE,DEMAND_TYPE,BUD_YEAR,DEMAND_NAME,demand_center_name,demand_dept_name,demand_sub_dept_name,DEMAND_STATUS_DESC,DEMAND_LINE_NUM,ITEM_NUM,ITEM_DESC,PRIMARY_UNIT_OF_MEASURE,item_type,user_name,DEMAND_QUANTITY,LIST_PRICE,PLAN_CODE,PLAN_NAME,PLAN_TYPE,PLAN_STATUS_DESC,PLAN_LINE_NUM,PLAN_QUANTITY,REQ_NUM,REQ_STATUS_DESC,BUYER_NAME,REQ_LINE_NUM,REQ_QUANTITY,AUCTION_HEADER_ID,AUCTION_TITLE,AUC_STATUS_DESC,AUC_LINE_NUM,AUC_QUANTITY,PO_NUM,PO_TYPE,PO_STATUS_DESC,VENDOR_NAME,PO_LINE_NUM,PO_PRICE,SHIP_QUANTITY,RECEIPT_NUM,LINE_NUM,QUANTITY_RECEIVED,DCODE,LN_NUM,QUANTITY_DELIVERED,CK_NUM,ORGANIZATION_NAME,PLAN_DEMAND_LINE_ID,DEMAND_APPROVE_DATE,DEMAND_CENTER_ID,DEMAND_CENTER_CODE,DEMAND_DEPT_ID,DEMAND_DEPT_CODE,DEMAND_SUB_DEPT_ID,DEMAND_SUB_DEPT_CODE,PLAN_CREATION_DATE,PLAN_ITEM_ID,ITEM_TYPE,PLAN_ITEM_NUM,PLAN_ITEM_DESC,PLAN_UOM,TRANS_QUANTITY,TRANS_SUBINV_CODE,PLAN_LIST_PRICE,SUGGESTED_SUBINV_CODE,PLAN_CENTER_ID,PLAN_CENTER_CODE,PLAN_CENTER_NAME,PLAN_DEPT_ID,PLAN_DEPT_CODE,PLAN_DEPT_NAME,PLAN_SUB_DEPT_ID,PLAN_SUB_DEPT_CODE,PLAN_SUB_DEPT_NAME,REQ_DISTRIBUTION_ID,DESTINATION_SUBINVENTORY,PO_HEADER_ID,APPROVED_DATE,PO_LINE_ID,PO_DISTRIBUTION_ID,QUANTITY_ORDERED,TRANSACTION_DATE,TRANS_COMMENTS,PLAN_COMMENTS,CREATION_DATE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,AGENT_NAME,AGENT_ID,VENDOR_ID FROM cux_inv_details_v WHERE 1=1 and ORGANIZATION_ID = 969 and DEMAND_TYPE = '季度' and BUD_YEAR = '2016' and ITEM_TYPE = '生产性' 
*/

SELECT
       DEMAND_CODE,
       BUD_YEAR,       
       DEMAND_TYPE,
       item_type,
       DEMAND_NAME,
       demand_center_name,
       demand_dept_name,
       demand_sub_dept_name,
       user_name,
       DEMAND_LINE_NUM,
       'A' || ITEM_NUM,
       LIST_PRICE,       
       -- 需要日期DATE
       '2016-07-07' 需要日期,
       C.demand_quantity,
       
       -- 年度数量
       '' 年度数量,
       -- 建议供应商
       '' 建议供应商,
       -- 备注：采购员
       '孙冠颖' 备注,
       -- 备用
       '' 备用
       /*,
       PO_NUM,
       PO_TYPE,
       PO_STATUS_DESC,
       PO_STATUS,
       PO_QUANTITY,
       LINE_LOCATION_ID,
       QUANTITY_ACCEPTED,
       QUANTITY_BILLED,
       VENDOR_ID
       */
       
  FROM cux_inv_details_v C
 WHERE 1 = 1
   and ORGANIZATION_ID = 969
   and BUD_YEAR = '2016'
   and DEMAND_STATUS='APPROVED'
   AND C.demand_type IN ('季度','月度','紧急')
   and PO_NUM is null
--   and c.item_type IN ('固定资产','非生产性')
   and c.demand_code not in ('SQ02201511090003','SQ02201511090004','SQ02201603260008','SQ02201601050002')
   -- 已导入 SQ02201603260008，SQ02201511090004,SQ02201511090003,SQ02201601050002
 ORDER BY 1 --c.item_type
;   
