SELECT 
       EMPLOYEE_ID,
       ORGANIZATION_ID,
       USER_ID,
USER_NAME,
       FULL_NAME,
       CENTER_ID,
       DEPT_ID,
       SUB_DEPT_ID,
       CENTER_NAME,
       DEPT_NAME,
       SUB_DEPT_NAME,
       INV_SUB,
       ATTRIBUTE1,
       DEFAULT_FLAG,
       ENABLED_FLAG,
       COMMENTS,
       ROW_ID,
       MAP_ID,
       CENTER_CODE,
       DEPT_CODE,
       SUB_DEPT_CODE,
       INV_SUB_DESC,
      
       CREATED_BY,
       CREATION_DATE,
       LAST_UPDATED_BY,
       LAST_UPDATE_DATE,
       LAST_UPDATE_LOGIN,
       ATTRIBUTE_CATEGORY
       /*,
       ATTRIBUTE2,
       ATTRIBUTE3,
       ATTRIBUTE4,
       ATTRIBUTE5,
       ATTRIBUTE6,
       ATTRIBUTE7,
       ATTRIBUTE8,
       ATTRIBUTE9,
       ATTRIBUTE10,
       ATTRIBUTE11,
       ATTRIBUTE12,
       ATTRIBUTE13,
       ATTRIBUTE14,
       ATTRIBUTE15*/
  FROM CUX_INV_USER_DEPT_MAP_V
 WHERE ORGANIZATION_ID in (102, 969)
   AND - 1 = -1
 order by user_name,organization_id
