
SELECT 
  SET_OF_BOOKS_ID, ORGANIZATION_ID, OPERATING_UNIT, ORGANIZATION_CODE,ORGANIZATION_NAME 
-- *
FROM ORG_ORGANIZATION_DEFINITIONS 
ORDER BY SET_OF_BOOKS_ID,ORGANIZATION_ID, OPERATING_UNIT;

/*3 - 运营    
X -
1 - 线路号
其中 304到330保留做线路
*/
