
SELECT * FROM DBA_USERS WHERE USERNAME IN ('FORM','UNIFORM');
--DEFAULT

SELECT * FROM DBA_PROFILES WHERE PROFILE='DEFAULT' AND RESOURCE_NAME='PASSWORD_LIFE_TIME';

--ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
