
use  szmetrouuv
--SELECT * FROM UUV_ADMIN;
SELECT TOP 10 * FROM SEC_USER;

USE SZMETROOA
SELECT TOP 10 * FROM SEC_USER
WHERE LOGINID='wuzhifan'


-- INSERT INTO UUV_ADMIN (ACCOUNTNAME) VALUES ('zhouweiwei1')
