SELECT 
       /*ROW_ID,
       LEDGER_ID,
       set_of_books_id,*/
--       TRANSACTION_ID,
       dept_id,
/*       SOURCE_CODE,
       SOURCE_TYPE,*/
       ORG_ID,
--       SUPPLY_CHANNEL,
       ASSET_UOM,
--       PROJECT_TYPE,
       SOURCE_QTY,
--       SOURCE_PRICE,
      ASSET_SITE,
--       PROJECT_SCOPE,
       CONFIRM_FLAG,
       IMPORT_FLAG,
       TRANSFER_ASSET_ID,
       UNIT_PRICE,
       trx_date,
       /*CREATED_BY,
       CREATION_DATE,
       LAST_UPDATED_BY,
       LAST_UPDATE_DATE,
       LAST_UPDATE_LOGIN,
       CONTEXT,
       ATTRIBUTE_CATEGORY_CODE,
       ATTRIBUTE1,
       ATTRIBUTE2,
       ATTRIBUTE3,
       ATTRIBUTE4,
       ATTRIBUTE5,
       ATTRIBUTE6,
       ATTRIBUTE7,
       ATTRIBUTE8,
       ATTRIBUTE9,*/
       ASSET_NUM,
       ASSET_NAME,
       ASSET_CATEGORY,
       ASSET_MODEL,
       CK_NUMBER,
       ASSET_QTY,
       ASSET_COST,
/*       CLOSED_COST,
       DEPRECIATION_VALUE,
       TOTAL_DEPRECIATION,
       SALVAGE_VALUE,
       DEPRN_METHOD,
       DEPRECIATION_YEAR,
       DEPRECIATION_MONTH,
       WORK_UNIT,
       WORK_CAPACITY,
       TRANSFER_DATE,*/
       BOOK_TYPE_NAME,
/*       CAP_ASSET_TYPE,
       ATTRIBUTE10,
       DEPRECIATION_START_DATE,
       DEPRECIATE_FLAG,
       PRORATE_CONVENTION_CODE,
       ASSIGNED_TO_NAME,
*/       BOOK_TYPE_CODE,
       TRANSFER_STATUS,
       ASSET_CCID,
       SOURCE_TRANSACTION_ID,
       SOURCE_ORG_ID,
       ASSET_KEY_CCID,
       LOCATION_ID,
       ASSIGNED_TO
  FROM cux_transfer_asset_v
 WHERE IMPORT_FLAG = 'N'
 and ck_number='CK201409290007'
 order by asset_num
