SELECT FLEX_VALUE_MEANING 物料类别,
       DESCRIPTION 描述,
       ENABLED_FLAG 是否启用,
       START_DATE_ACTIVE 生效日期,
       END_DATE_ACTIVE 失效日期,
       HIERARCHY_LEVEL + 1 级别
  FROM FND_FLEX_VALUES_VL
 WHERE (('' IS NULL) OR
       (STRUCTURED_HIERARCHY_LEVEL IN
       (SELECT HIERARCHY_ID
            FROM FND_FLEX_HIERARCHIES_VL H
           WHERE H.FLEX_VALUE_SET_ID = 1015085
             AND H.HIERARCHY_NAME LIKE '')))
   AND (FLEX_VALUE_SET_ID = 1015085)
 ORDER BY FLEX_VALUE
