SELECT B.ASSET_NUMBER 资产编号,
b.serial_number 资产序列号,
       T.DESCRIPTION 资产描述,
       TH.TRANSACTION_HEADER_ID 事务处理编号,
       DECODE(TH.TRANSACTION_HEADER_ID,
              DH.TRANSACTION_HEADER_ID_IN,
              '至',
              DH.TRANSACTION_HEADER_ID_OUT,
              '自') 自至,
       TO_CHAR(TH.TRANSACTION_DATE_ENTERED,
               'RRRR-MM') 期间,
       TH.TRANSACTION_DATE_ENTERED 事务处理日期,
       PAPF.LAST_NAME 员工姓名,
       ASCC.CODE_COMBINATION_ID CCID,
       ASCC.SEGMENT1 公司,
       ASCC.SEGMENT2 成本中心,
       ASCC.SEGMENT3 费用账户,
       FFVV1.DESCRIPTION 账户描述,
       LOC.SEGMENT1 || '.' || LOC.SEGMENT2 || '.' || LOC.SEGMENT3 资产地点,
       FFVV2.DESCRIPTION || '.' || FFVV3.DESCRIPTION || '.' ||
       FFVV4.DESCRIPTION 资产地点描述,
       
       SUM(CADJ.ADJUSTMENT_AMOUNT * DECODE(CADJ.DEBIT_CREDIT_FLAG,
                                           'CR',
                                           -1,
                                           'DR',
                                           1)) 分配成本,
       0 折旧准备,
       SUM(DISTINCT DECODE(TH.TRANSACTION_HEADER_ID,
                  DH.TRANSACTION_HEADER_ID_IN,
                  1,
                  DH.TRANSACTION_HEADER_ID_OUT,
                  -1) * DH.UNITS_ASSIGNED) 数量
  FROM FA_LOCATIONS            LOC,
       FA_ADDITIONS_B          B,
       FA_ADDITIONS_TL         T,
       GL_CODE_COMBINATIONS    ASCC,
       FA_DISTRIBUTION_HISTORY DH,
       FA_TRANSACTION_HEADERS  TH,
       FA_ADJUSTMENTS          CADJ,
       PER_ALL_PEOPLE_F        PAPF,
       FND_FLEX_VALUE_SETS     FFVS1,
       FND_FLEX_VALUES_VL      FFVV1,
       FND_FLEX_VALUE_SETS     FFVS2,
       FND_FLEX_VALUES_VL      FFVV2,
       FND_FLEX_VALUE_SETS     FFVS3,
       FND_FLEX_VALUES_VL      FFVV3,
       FND_FLEX_VALUE_SETS     FFVS4,
       FND_FLEX_VALUES_VL      FFVV4

 WHERE TH.BOOK_TYPE_CODE = '301_FA'
   AND DH.ASSIGNED_TO = PAPF.PERSON_ID
   AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND
       PAPF.EFFECTIVE_END_DATE
   AND TH.TRANSACTION_TYPE_CODE = 'TRANSFER'
   --AND TO_CHAR(TH.TRANSACTION_DATE_ENTERED,
  --             'RRRR-MM') = '2012-08'
   AND NVL(TH.MASS_REFERENCE_ID,
           0) = NVL(NULL,
                    NVL(TH.MASS_REFERENCE_ID,
                        0))
   AND (TH.TRANSACTION_HEADER_ID = DH.TRANSACTION_HEADER_ID_IN OR
       TH.TRANSACTION_HEADER_ID = DH.TRANSACTION_HEADER_ID_OUT)
   AND T.ASSET_ID = TH.ASSET_ID
   AND LOC.LOCATION_ID = DH.LOCATION_ID
   AND ASCC.CODE_COMBINATION_ID = DH.CODE_COMBINATION_ID
   AND CADJ.BOOK_TYPE_CODE = '301_FA'
   AND CADJ.ASSET_ID = TH.ASSET_ID
   AND CADJ.DISTRIBUTION_ID = DH.DISTRIBUTION_ID
   AND CADJ.TRANSACTION_HEADER_ID = TH.TRANSACTION_HEADER_ID
   AND CADJ.SOURCE_TYPE_CODE = 'TRANSFER'
   AND CADJ.ADJUSTMENT_TYPE IN ('COST',
                                'CIP COST')
   AND T.LANGUAGE = 'ZHS'
   AND B.ASSET_ID = T.ASSET_ID
   AND ASCC.SEGMENT3 = FFVV1.FLEX_VALUE
   AND FFVV1.FLEX_VALUE_SET_ID = FFVS1.FLEX_VALUE_SET_ID
   AND FFVS1.FLEX_VALUE_SET_NAME = 'SZMTR_GL_YYACC'
   AND LOC.SEGMENT1 = FFVV2.FLEX_VALUE
   AND FFVV2.FLEX_VALUE_SET_ID = FFVS2.FLEX_VALUE_SET_ID
   AND FFVS2.FLEX_VALUE_SET_NAME = 'SZMTR_FA_COM'
   AND LOC.SEGMENT2 = FFVV3.FLEX_VALUE
   AND FFVV3.FLEX_VALUE_SET_ID = FFVS3.FLEX_VALUE_SET_ID
   AND FFVS3.FLEX_VALUE_SET_NAME = 'SZMTR_GL_CC'
   AND LOC.SEGMENT3 = FFVV4.FLEX_VALUE
   AND FFVV4.FLEX_VALUE_SET_ID = FFVS4.FLEX_VALUE_SET_ID
   AND FFVS4.FLEX_VALUE_SET_NAME = 'FA_LOC'
 GROUP BY TH.TRANSACTION_HEADER_ID,
 b.serial_number,
          DECODE(TH.TRANSACTION_HEADER_ID,
                 DH.TRANSACTION_HEADER_ID_IN,
                 '至',
                 DH.TRANSACTION_HEADER_ID_OUT,
                 '自'),
          DH.DISTRIBUTION_ID,
          B.ASSET_NUMBER,
          T.DESCRIPTION,
          TO_CHAR(TH.TRANSACTION_DATE_ENTERED,
                  'RRRR-MM'),
          TH.TRANSACTION_DATE_ENTERED,
          PAPF.LAST_NAME,
          ASCC.SEGMENT1,
          ASCC.SEGMENT2,
          ASCC.SEGMENT3,
          LOC.SEGMENT1 || '.' || LOC.SEGMENT2 || '.' || LOC.SEGMENT3,
          FFVV1.DESCRIPTION,
          FFVV2.DESCRIPTION || '.' || FFVV3.DESCRIPTION || '.' ||
          FFVV4.DESCRIPTION,
          ASCC.CODE_COMBINATION_ID
