
SELECT 
--        *
    SEGMENT1,
    organization_id,
       DEPT_NAME,
       ITEM_CATEGORY1,
       ITEM_CATEGORY2,
       ENABLED_FLAG,
       COMMENTS,
       MAP_ID,
       DEPT_CODE,
       DEPT_ID,
       SEGMENT3,
       SEGMENT4,
       SEGMENT2,
       ORGANIZATION_ID,
       SEGMENT5,
       SEGMENT6,
       SEGMENT7,
       SEGMENT8,
       ITEM_CATEGORY3,
       CREATED_BY,
       CREATION_DATE,
       LAST_UPDATED_BY,
       LAST_UPDATE_DATE,
       LAST_UPDATE_LOGIN /*,
       ATTRIBUTE_CATEGORY,
       ATTRIBUTE1,
       ATTRIBUTE2,
       ATTRIBUTE3,
       ATTRIBUTE4,
       ATTRIBUTE5,
       ATTRIBUTE6,
       ATTRIBUTE7,
       ATTRIBUTE8,
       ATTRIBUTE9,
       ATTRIBUTE10,
       ATTRIBUTE11,
       ATTRIBUTE12,
       ATTRIBUTE13,
       ATTRIBUTE14,
       ATTRIBUTE15,*/
       -- ROW_ID
 FROM CUX_INV_DEPT_CAT_MAP_V
 WHERE ORGANIZATION_ID = 1359
--   AND - 1 = -1
 order by SEGMENT1£¬SEGMENT2£¬ITEM_CATEGORY1
